/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */
/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The top-level napi class exposed to JavaScript.
 *
 * `UniffiNativeModule` is the entry point for loading a UniFFI shared library
 * and registering its function definitions. JS code calls `open(path)` to
 * dlopen the library, then `register(definitions)` to parse the type
 * descriptions and produce a JS object whose methods invoke the foreign
 * functions through libffi.
 */
export declare class UniffiNativeModule {
  /** Load a shared library from the given filesystem path via `dlopen`. */
  static open(path: string): UniffiNativeModule
  /**
   * Parse JS-provided type definitions and produce a JS object whose methods
   * are bound to the foreign functions found in the loaded library.
   */
  register(definitions: object): object
}
