/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The top-level napi class exposed to JavaScript.
 *
 * `UniffiNativeModule` is the entry point for loading a UniFFI shared library
 * and registering its function definitions. JS code calls `open(path)` to
 * store the library path, then `register(definitions)` to parse the type
 * descriptions, create a `Module` (which opens the library), and produce a
 * JS object whose methods invoke the foreign functions.
 */
export declare class UniffiNativeModule {
  /**
   * Validate the library path and store it for later use by `register()`.
   *
   * The library is not fully opened here — `Module::new()` in `register()`
   * handles `dlopen`, symbol resolution, and CIF construction in one step.
   * However, we do a trial `dlopen` to validate the path eagerly, so that
   * callers get an immediate error for invalid paths rather than a deferred
   * error at `register()` time.
   *
   * The trial `LibraryHandle` is simply dropped. Because `LibraryHandle`
   * wraps `ManuallyDrop<Library>`, dropping it does NOT call `dlclose` —
   * the library stays mapped, which is fine because `Module::new()` will
   * re-open (or find the already-mapped) library shortly after.
   */
  static open(path: string): UniffiNativeModule
  /**
   * Parse JS-provided type definitions and produce a JS object whose methods
   * are bound to the foreign functions found in the loaded library.
   */
  register(definitions: object): object
  /**
   * Unload the native module, draining in-flight calls and optionally force-closing
   * the shared library.
   *
   * Accepts an optional options object with a `force` boolean field. When
   * `{ force: true }` is passed, `dlclose` is called on the library after
   * all in-flight calls have drained. Without `force`, the unloading flag is
   * set and callbacks are aborted, but the library mapping is left in place.
   *
   * After `unload()` returns, this `UniffiNativeModule` no longer holds a
   * reference to the `Module` — any JS closures that captured the module will
   * still hold their `Arc<Module>` references until they are garbage-collected.
   */
  unload(options?: object | undefined | null): void
}
