# Generated by uniffi-bindgen-react-native
{%- let android = self.config.project.android.clone() %}
-dontwarn java.awt.*
-keep class com.sun.jna.* { *; }
-keepclassmembers class * extends com.sun.jna.* { public *; }
-keep class {{ android.package_name() }}.** { *; }