// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

// This template is only used when running `cargo xtask run`, i.e. when running `./scripts/run-tests.sh`.
// It is an implementation of the `registerNatives` function which is used by the test-runner to dynamically
// load the native modules without re-compiling the test-runner.
//
// Files generated with this template appear in the fixtures/{fixture}/generated/cpp directory, always called
// `Entrypoint.cpp`, with a captilized `E` to ensure it does not collide with namespaces called "entrypoint".

#include "registerNatives.h"

{%- for m in modules %}
#include "{{ m.hpp_filename() }}"
{%- endfor %}

extern "C" void registerNatives(jsi::Runtime &rt, std::shared_ptr<react::CallInvoker> callInvoker) {
    {%- for m in modules %}
    {{ m.cpp_module() }}::registerModule(rt, callInvoker);
    {%- endfor %}
}
