/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */

use anyhow::Result;
use clap::{Args, Subcommand};
use ubrn_bindgen::{ModuleMetadata, OutputArgs, SourceArgs, SwitchArgs};

use crate::{
    codegen::{get_template_config, render_files},
    commands::ConfigArgs,
    wasm, ProjectConfig,
};

#[derive(Args, Debug)]
pub(crate) struct CmdArg {
    #[clap(subcommand)]
    cmd: Cmd,
}
impl CmdArg {
    pub(crate) fn run(&self) -> Result<()> {
        self.cmd.run()
    }
}

#[derive(Debug, Subcommand)]
enum Cmd {
    /// Generate just the Typescript and wasm-bindgen bindings
    Bindings(BindingsArgs),

    /// Generate the Cargo.toml and entrypoints to the bindings
    WasmCrate(WasmCrateArgs),
}

impl Cmd {
    fn run(&self) -> Result<()> {
        match self {
            Self::Bindings(b) => {
                let b = ubrn_bindgen::BindingsArgs::from(b);
                b.run(None)?;
                Ok(())
            }
            Self::WasmCrate(c) => {
                c.run()?;
                Ok(())
            }
        }
    }
}

#[derive(Args, Debug)]
struct BindingsArgs {
    #[command(flatten)]
    pub(crate) source: SourceArgs,
    #[command(flatten)]
    pub(crate) output: OutputArgs,
}

impl From<&BindingsArgs> for ubrn_bindgen::BindingsArgs {
    fn from(value: &BindingsArgs) -> Self {
        ubrn_bindgen::BindingsArgs::new(
            SwitchArgs {
                flavor: ubrn_bindgen::AbiFlavor::Wasm,
            },
            value.source.clone(),
            value.output.clone(),
        )
    }
}

#[derive(Args, Debug)]
pub(crate) struct WasmCrateArgs {
    #[clap(flatten)]
    config: ConfigArgs,

    /// The namespaces that are generated by `generate wasm bindings`.
    namespaces: Vec<String>,
}

impl WasmCrateArgs {
    pub(crate) fn run(&self) -> Result<()> {
        let project = ProjectConfig::try_from(self.config.clone())?;
        let modules = self
            .namespaces
            .iter()
            .map(|s| ModuleMetadata::new(s))
            .collect();
        let rust_crate = project.crate_.metadata()?;
        let config = get_template_config(project, rust_crate, modules, false);
        let files = wasm::get_files(config.clone());
        render_files(config.clone(), files.into_iter())?;
        Ok(())
    }
}
