//! # uniffi-runtime-napi: A dynamic FFI bridge from Node.js to UniFFI-generated Rust libraries
//!
//! This crate is a Node.js native addon built with [napi-rs](https://napi.rs/) that provides
//! a **dynamic** foreign function interface bridge for libraries generated by
//! [UniFFI](https://mozilla.github.io/uniffi-rs/). Unlike conventional approaches that
//! require compile-time code generation for each target library, this bridge operates
//! entirely at runtime: it loads shared libraries via `dlopen`, resolves their exported
//! C symbols via `dlsym`, and invokes them through [libffi](https://docs.rs/libffi)'s
//! call-interface (CIF) mechanism.
//!
//! ## How it works
//!
//! The bridge is **driven by type definitions supplied from JavaScript**. No Rust code
//! generation is needed per target library. The flow is:
//!
//! 1. JS describes function signatures as tagged objects (e.g., `{ tag: 'Int32' }`).
//! 2. Rust parses these into [`FfiTypeDesc`](ffi_type::FfiTypeDesc) values.
//! 3. The CIF layer ([`cif`]) maps each `FfiTypeDesc` to a concrete `libffi::middle::Type`,
//!    constructing the call-interface descriptor that libffi needs.
//! 4. At call time, Rust marshals JS values into C-compatible argument buffers, invokes
//!    the foreign function through libffi, and unmarshals the result back to JS.
//!
//! ## Main-thread detection and the two-path callback design
//!
//! Node.js's N-API values can only be created and accessed on the **main thread** (the
//! thread running the event loop). However, Rust libraries may invoke callbacks from
//! arbitrary worker threads. This fundamental tension drives the two-path design that
//! pervades the callback system:
//!
//! - **Same-thread path**: When a callback fires on the main thread, we can directly
//!   construct napi values and call into JS synchronously.
//! - **Cross-thread path**: When a callback fires on a worker thread, we must use a
//!   threadsafe function (TSF) to schedule the call back onto the main thread's event
//!   loop, then block the worker until the result is available.
//!
//! The [`MAIN_THREAD_ID`] static captures the main thread's identity at module
//! initialization time, and [`is_main_thread`] is the single predicate that every
//! callback path consults to choose between these two strategies.

use std::sync::OnceLock;
use std::thread::ThreadId;

use napi::bindgen_prelude::*;
use napi::module_init;
use napi::JsObject;
use napi_derive::napi;

mod callback;
mod cif;
mod ffi_c_types;
mod ffi_type;
mod fn_pointer;
mod library;
mod marshal;
mod napi_utils;
mod register;
mod structs;

use library::LibraryHandle;

/// The identity of the main Node.js thread, captured once at module initialization.
/// Used by [`is_main_thread`] to determine whether callback code can access napi
/// values directly or must dispatch through a threadsafe function.
static MAIN_THREAD_ID: OnceLock<ThreadId> = OnceLock::new();

#[module_init]
fn init() {
    MAIN_THREAD_ID
        .set(std::thread::current().id())
        .expect("module_init called twice");
}

/// Returns `true` if the calling thread is the main Node.js event-loop thread.
///
/// This is the single decision point for the callback system's two-path design:
/// when `true`, napi values can be manipulated directly; when `false`, work must
/// be dispatched to the main thread via a threadsafe function.
pub fn is_main_thread() -> bool {
    MAIN_THREAD_ID
        .get()
        .is_some_and(|id| *id == std::thread::current().id())
}

/// The top-level napi class exposed to JavaScript.
///
/// `UniffiNativeModule` is the entry point for loading a UniFFI shared library
/// and registering its function definitions. JS code calls `open(path)` to
/// dlopen the library, then `register(definitions)` to parse the type
/// descriptions and produce a JS object whose methods invoke the foreign
/// functions through libffi.
#[napi]
pub struct UniffiNativeModule {
    handle: LibraryHandle,
}

#[napi]
impl UniffiNativeModule {
    /// Load a shared library from the given filesystem path via `dlopen`.
    #[napi(factory)]
    pub fn open(path: String) -> napi::Result<Self> {
        let handle = LibraryHandle::open(&path)?;
        Ok(Self { handle })
    }

    /// Parse JS-provided type definitions and produce a JS object whose methods
    /// are bound to the foreign functions found in the loaded library.
    #[napi]
    pub fn register(&self, env: Env, definitions: JsObject) -> napi::Result<JsObject> {
        register::register(env, &self.handle, definitions)
    }
}
