/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */
//! # uniffi-runtime-napi: A dynamic FFI bridge from Node.js to UniFFI-generated Rust libraries
//!
//! This crate is a Node.js native addon built with [napi-rs](https://napi.rs/) that provides
//! a **dynamic** foreign function interface bridge for libraries generated by
//! [UniFFI](https://mozilla.github.io/uniffi-rs/). Unlike conventional approaches that
//! require compile-time code generation for each target library, this bridge operates
//! entirely at runtime: it loads shared libraries via `dlopen`, resolves their exported
//! C symbols via `dlsym`, and invokes them through trampolines built by
//! `uniffi-runtime-core`.
//!
//! ## How it works
//!
//! The bridge is **driven by type definitions supplied from JavaScript**. No Rust code
//! generation is needed per target library. The flow is:
//!
//! 1. JS describes function signatures as tagged objects (e.g., `{ tag: 'Int32' }`).
//! 2. Rust parses these into [`FfiTypeDesc`](uniffi_runtime_core::FfiTypeDesc) values
//!    via [`spec_from_js`].
//! 3. `uniffi-runtime-core` maps each `FfiTypeDesc` to native types and builds the
//!    call-interface descriptors needed to invoke foreign functions.
//! 4. At call time, Rust marshals JS values into C-compatible argument buffers, invokes
//!    the foreign function via core, and unmarshals the result back to JS.
//!
//! ## Owning-thread detection and the two-path callback design
//!
//! Node.js's N-API values can only be created and accessed on the JS thread that owns
//! them. However, Rust libraries may invoke callbacks from arbitrary worker threads.
//! This fundamental tension drives the two-path design that pervades the callback
//! system:
//!
//! - **Same-thread path**: When a callback fires on the JS thread that registered it, we
//!   can directly construct napi values and call into JS synchronously.
//! - **Cross-thread path**: When a callback fires on any other thread, we must use a
//!   threadsafe function to schedule the call back onto the owning thread's event
//!   loop, then block the calling thread until the result is available.
//!
//! [`callback::is_js_thread`] is the single predicate every callback path consults to choose
//! between these two strategies, and it answers per callback: each callback records the thread
//! that registered it, alongside the `napi_env` and `ThreadsafeFunction` it already held for that
//! same thread.

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, MutexGuard, OnceLock, PoisonError};

use napi::bindgen_prelude::*;
use napi::JsObject;
use napi_derive::napi;

mod call;
mod callback;
mod napi_utils;
mod register;

use std::sync::Arc;
use uniffi_runtime_core::Module;

/// Convert a core error into a napi error.
pub(crate) fn core_err(e: uniffi_runtime_core::Error) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// Per-environment state for coordinating shutdown and tracking VTable TSFNs.
///
/// During env cleanup (triggered when that environment is torn down, which for a worker happens
/// long before the process exits), the hook sets `shutdown` to `true` and aborts that
/// environment's TSFNs. Aborting drops pending calls and their `SyncSender`s, which unblocks any
/// Rust worker threads that are waiting on `rx.recv()`. This prevents SIGSEGV crashes on Linux
/// where the shared library would otherwise be `dlclose()`'d while Rust threads still hold
/// function pointers into it.
///
/// Per environment rather than per process: a TSFN is bound to the event loop of the environment
/// that created it, so one environment's teardown must neither abort another's handles nor mark
/// another's callbacks as shutting down.
pub struct EnvState {
    /// A hint, read on every callback invocation so the hot path takes no lock. The list below is
    /// the authority: a registration racing teardown is refused by `register_tsfn`, not by this.
    shutdown: AtomicBool,
    /// This environment's VTable TSFN handles while it lives, and `None` once it is torn down.
    ///
    /// One `Option` rather than a separate flag and list, because registering and sweeping have to
    /// be the same decision under the same lock. As two pieces of state, a handle could be pushed
    /// after the sweep had already passed it, leaving it bound to an event loop that no longer
    /// exists with nothing left to abort it.
    tsfns: Mutex<Option<Vec<TsfnHandle>>>,
}

/// A `napi_threadsafe_function`, as a value that may cross threads.
///
/// The newtype exists for the two impls below. They are the only `unsafe` this needs, and putting
/// them here rather than on [`EnvState`] keeps them off the fields that never wanted them.
#[derive(Clone, Copy)]
struct TsfnHandle(napi::sys::napi_threadsafe_function);

// SAFETY: napi's threadsafe function APIs are explicitly callable from any thread, which is the
// whole purpose of the type. This is an opaque handle that is never dereferenced here, only handed
// back to `napi_release_threadsafe_function`.
unsafe impl Send for TsfnHandle {}
unsafe impl Sync for TsfnHandle {}

impl EnvState {
    fn new() -> Self {
        Self {
            shutdown: AtomicBool::new(false),
            tsfns: Mutex::new(Some(Vec::new())),
        }
    }

    /// Returns `true` if the owning Node.js environment is shutting down.
    ///
    /// Callback trampolines check this before attempting any work, so they can
    /// bail out early rather than touching a half-torn-down JS environment.
    pub fn is_shutting_down(&self) -> bool {
        self.shutdown.load(Ordering::Acquire)
    }

    /// Register a VTable TSFN raw handle so this environment's cleanup hook can abort it.
    ///
    /// A handle arriving after the environment has been torn down is aborted here instead: its
    /// sweep has already passed, so nothing else ever would. Callers get one rule rather than a
    /// result to remember, and the decision stays with the state that knows the answer.
    ///
    /// # Safety
    ///
    /// `raw` must be a live threadsafe function this environment owns, and ownership of it passes
    /// here: the caller must not release it, because this either stores it for the teardown sweep
    /// or aborts it on the spot.
    pub unsafe fn register_tsfn(&self, raw: napi::sys::napi_threadsafe_function) {
        let orphaned = match &mut *self.tsfns() {
            Some(live) => {
                live.push(TsfnHandle(raw));
                false
            }
            None => true,
        };
        // Outside the guard, for the reason `close` gives: aborting is a call into napi that
        // unblocks other threads, and it has no business happening under this lock.
        if orphaned {
            // SAFETY: an opaque handle the caller just created and never dereferences. `abort`
            // drops pending calls, which is what releases anything already waiting on it.
            unsafe {
                napi::sys::napi_release_threadsafe_function(
                    raw,
                    napi::sys::ThreadsafeFunctionReleaseMode::abort,
                );
            }
        }
    }

    /// Close this environment to new handles and take the ones it holds.
    ///
    /// The guard is released with the returned value, so the caller aborts without holding the
    /// lock. That matters: aborting unblocks Rust worker threads, and one of those may re-enter
    /// through a callback before the sweep has finished.
    fn close(&self) -> Vec<TsfnHandle> {
        self.shutdown.store(true, Ordering::Release);
        self.tsfns().take().unwrap_or_default()
    }

    /// A poisoned lock means a panic while the list was held. It guards a list of opaque handles
    /// with no cross-field invariant a panic could break, and a panic raised from here would cross
    /// the napi boundary as an abort, so recovering beats taking the host process down.
    fn tsfns(&self) -> MutexGuard<'_, Option<Vec<TsfnHandle>>> {
        self.tsfns.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

/// Every environment that has registered a module, keyed by its raw `napi_env`.
///
/// Touched when a callback is created and when an environment is torn down, both cold paths. A
/// callback invocation reads its own `Arc<EnvState>` out of its user data, so the hot path takes
/// no lock.
static ENV_STATES: OnceLock<Mutex<HashMap<usize, Arc<EnvState>>>> = OnceLock::new();

/// Recovered rather than propagated, for the reason [`EnvState::tsfns`] gives: a panic raised from
/// here would cross the napi boundary as an abort.
fn env_states() -> MutexGuard<'static, HashMap<usize, Arc<EnvState>>> {
    ENV_STATES
        .get_or_init(|| Mutex::new(HashMap::new()))
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
}

/// The state for `raw_env`, created on first use.
pub fn env_state(raw_env: napi::sys::napi_env) -> Arc<EnvState> {
    Arc::clone(
        env_states()
            .entry(raw_env as usize)
            .or_insert_with(|| Arc::new(EnvState::new())),
    )
}

/// Env cleanup hook, called by Node.js when an environment is torn down.
///
/// # Safety
/// Called by the napi runtime with the `data` pointer we registered, which is the raw `napi_env`
/// this hook was installed for.
unsafe extern "C" fn env_cleanup_hook(data: *mut std::ffi::c_void) {
    // Removed in a statement of its own, so the table's lock is released before anything below.
    let removed = env_states().remove(&(data as usize));
    let Some(state) = removed else {
        return;
    };

    // `close` marks the environment shut, takes its handles, and releases its own lock before
    // handing them back. Aborting drops pending calls (and their SyncSenders), which unblocks Rust
    // worker threads waiting on `rx.recv()` — and one of those may come straight back through a
    // callback, so it must not find this sweep still holding the lock it needs.
    for handle in state.close() {
        unsafe {
            napi::sys::napi_release_threadsafe_function(
                handle.0,
                napi::sys::ThreadsafeFunctionReleaseMode::abort,
            );
        }
    }
}

/// Install the cleanup hook for `env`, once per environment.
///
/// Every environment needs its own: a worker's TSFNs are bound to the worker's event loop, and are
/// only safe for that environment's teardown to abort.
fn install_env_cleanup_hook(env: &Env) {
    let raw = env.raw();
    let key = raw as usize;
    {
        let mut states = env_states();
        if states.contains_key(&key) {
            return;
        }
        states.insert(key, Arc::new(EnvState::new()));
    }
    unsafe {
        napi::sys::napi_add_env_cleanup_hook(raw, Some(env_cleanup_hook), raw.cast());
    }
}

/// The top-level napi class exposed to JavaScript.
///
/// `UniffiNativeModule` is the entry point for loading a UniFFI shared library
/// and registering its function definitions. JS code calls `open(path)` to
/// store the library path, then `register(definitions)` to parse the type
/// descriptions, create a `Module` (which opens the library), and produce a
/// JS object whose methods invoke the foreign functions.
#[napi]
pub struct UniffiNativeModule {
    /// The filesystem path to the shared library. Stored by `open()`, used by
    /// `register()` to create a `Module` (which handles `dlopen` internally).
    library_path: String,
    /// The `Module` created by `register()`. `None` until `register()` is called.
    module: Option<Arc<Module>>,
}

#[napi]
impl UniffiNativeModule {
    /// Validate the library path and store it for later use by `register()`.
    ///
    /// The library is not fully opened here — `Module::new()` in `register()`
    /// handles `dlopen`, symbol resolution, and CIF construction in one step.
    /// However, we do a trial `dlopen` to validate the path eagerly, so that
    /// callers get an immediate error for invalid paths rather than a deferred
    /// error at `register()` time.
    ///
    /// The trial `LibraryHandle` is simply dropped. Because `LibraryHandle`
    /// wraps `ManuallyDrop<Library>`, dropping it does NOT call `dlclose` —
    /// the library stays mapped, which is fine because `Module::new()` will
    /// re-open (or find the already-mapped) library shortly after.
    #[napi(factory)]
    pub fn open(path: String) -> napi::Result<Self> {
        // Trial open to validate the path. Drop does not dlclose.
        let _handle = uniffi_runtime_core::LibraryHandle::open(&path).map_err(core_err)?;
        Ok(Self {
            library_path: path,
            module: None,
        })
    }

    /// Parse JS-provided type definitions and produce a JS object whose methods
    /// are bound to the foreign functions found in the loaded library.
    #[napi]
    pub fn register(&mut self, env: Env, definitions: JsObject) -> napi::Result<JsObject> {
        // Install the env cleanup hook on the first register call. This is the
        // earliest point where we have a valid `Env` (the `#[module_init]` ctor
        // runs before the napi env exists).
        install_env_cleanup_hook(&env);
        let (result, module) = register::register(env, &self.library_path, definitions)?;
        self.module = Some(module);
        Ok(result)
    }

    /// Unload the native module, draining in-flight calls and optionally force-closing
    /// the shared library.
    ///
    /// Accepts an optional options object with a `force` boolean field. When
    /// `{ force: true }` is passed, `dlclose` is called on the library after
    /// all in-flight calls have drained. Without `force`, the unloading flag is
    /// set and callbacks are aborted, but the library mapping is left in place.
    ///
    /// After `unload()` returns, this `UniffiNativeModule` no longer holds a
    /// reference to the `Module` — any JS closures that captured the module will
    /// still hold their `Arc<Module>` references until they are garbage-collected.
    #[napi]
    pub fn unload(&mut self, options: Option<JsObject>) -> napi::Result<()> {
        let force = match &options {
            Some(o) => o.get_named_property::<bool>("force").unwrap_or(false),
            None => false,
        };
        if let Some(module) = self.module.take() {
            if force {
                module.unload_force().map_err(core_err)?;
            } else {
                module.unload().map_err(core_err)?;
            }
        }
        Ok(())
    }
}
