[general]
dirs = [
    "templates/fixtures",
    "templates/jsi/crossplatform",
    "templates/jsi/android",
    "templates/jsi/ios",
    "templates/wasm",
]
default_syntax = "none"

[[syntax]]
name = "none"
