// Generated by uniffi-bindgen-react-native
#include "{{ self.config.project.cpp_filename() }}.h"
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.cpp_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
{%- for m in self.config.modules %}
#include "{{ bindings }}/{{ m.hpp_filename() }}"
{%- endfor %}

namespace {{ self.config.project.cpp_namespace() }} {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
        {%- for m in self.config.modules %}
		{{ m.cpp_module() }}::registerModule(runtime, callInvoker);
        {%- endfor %}
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}
