// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

// wasm-bindgen glue for the module staged beside this file.
export {};
