[package]
name = "my-test-crate"
version = "0.1.0"
authors = ["James Hugman <james@hugman.tv>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
# We want to ensure that the version of wasm-bindgen is selected by the
# uniffi-runtime-javascript crate.
# cargo is smart enough to do this if we don't put any further restrictions
# on it.
wasm-bindgen = "*"
{{crate_name}} = { path = "{{crate_path}}" }
uniffi-runtime-javascript = { path = "{{uniffi_runtime_javascript}}", features = ["wasm32"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[workspace]

[workspace.dependencies]
wasm-bindgen = "*"
