// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include "{{ self.config.project.cpp_filename() }}.h"
{%- let package_name = self.config.project.android.package_name.replace(".", "_") %}
{%- let name = self.config.project.name_upper_camel() %}
{%- let module_class_name = name|fmt("{}Module") %}
{%- let prefix = "Java_{}_{}"|format(package_name, module_class_name) %}

using namespace facebook;

extern "C"
JNIEXPORT jdouble JNICALL
{{ prefix }}_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return matrixrustsdk::multiply(a, b);
}

// Installer coming from {{ module_class_name }}
extern "C"
JNIEXPORT jboolean JNICALL
{{ prefix }}_nativeInstallRustCrate(JNIEnv *env, jclass type, jlong rtPtr, jboolean a) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return matrixrustsdk::installRustCrate(*runtime, a);
}

extern "C"
JNIEXPORT jboolean JNICALL
{{ prefix }}_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr, jboolean a) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return matrixrustsdk::installRustCrate(*runtime, a);
}
