// Generated by uniffi-bindgen-react-native
import installer from './{{ self.config.project.codegen_filename() }}';

// Register the rust crate with Hermes
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
{%- for m in self.config.modules %}
export * from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
{%- for m in self.config.modules %}
import * as {{ m.ts() }} from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}

// Initialize the generated bindings: mostly checksums, but also callbacks.
let initialized = false;
if (!initialized) {
  {%- for m in self.config.modules %}
  {{ m.ts() }}.default.initialize();
  {%- endfor %}
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
{%- for m in self.config.modules %}
  {{ m.ts() }},
{%- endfor %}
};

{# space #}
