// Generated by uniffi-bindgen-react-native
import installer from './{{ self.config.project.codegen_filename() }}';

// Register the rust crate with Hermes
installer.installRustCrate(true);

// TODO Remove `multiply` after seeing this work on iOS and Android.
export function multiply(a: number, b: number): number {
  return installer.multiply(a, b);
}

// Export the generated bindings to the app.
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
{%- for m in self.config.modules %}
export * from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}
