// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "{{ self.config.project.cpp_filename() }}.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "{{ self.config.project.tm.name() }}.h"

@interface {{ self.config.project.name_upper_camel() }} : NSObject <{{ self.config.project.tm.spec_name() }}>
#else
#import <React/RCTBridgeModule.h>

@interface {{ self.config.project.name_upper_camel() }} : NSObject <RCTBridgeModule>
#endif

@end
