// Generated by uniffi-bindgen-react-native
#include "{{ self.config.project.cpp_filename() }}.h"
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.cpp_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
{%- for m in self.config.modules %}
#include "{{ bindings }}/{{ m.hpp_filename() }}"
{%- endfor %}

namespace matrixrustsdk {
	using namespace facebook;
	double multiply(double a, double b) {
		return a * b;
	}

	uint8_t installRustCrate(jsi::Runtime &runtime, uint8_t b) {
        {%- for m in self.config.modules %}
		{{ m.cpp_module() }}::registerModule(runtime);
        {%- endfor %}
		return false;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime, uint8_t b) {
		return false;
	}
}
