// Generated by uniffi-bindgen-react-native — do not edit.
{%- for m in modules %}
export * from './{{ m.ts() }}';
{%- endfor %}

{%- for m in modules %}
import * as {{ m.ts() }} from './{{ m.ts() }}';
{%- endfor %}

{% if flavor.supports_sync_initialization() %}
let initialized = false;
if (!initialized) {
  {%- for m in modules %}
  {{ m.ts() }}.default.initialize();
  {%- endfor %}
  initialized = true;
}

export async function uniffiInitAsync() { /* sync flavor: no-op */ }
{% else %}
let initPromise: Promise<void> | undefined;
export function uniffiInitAsync(): Promise<void> {
  if (!initPromise) {
    initPromise = (async () => {
      {%- for m in modules %}
      await {{ m.ts() }}.default.initialize();
      {%- endfor %}
    })();
  }
  return initPromise;
}
{% endif %}

export default {
{%- for m in modules %}
  {{ m.ts() }},
{%- endfor %}
};
