// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

import lib from "@ubjs/node";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "{{ module.symbols.rustbuffer_alloc }}",
    rustbuffer_free: "{{ module.symbols.rustbuffer_free }}",
    rustbuffer_from_bytes: "{{ module.symbols.rustbuffer_from_bytes }}",
  },
  functions: {
    {%- for func in module.functions %}
    "{{ func.name }}": {
      args: [{{ func.args.join(", ") }}],
      ret: {{ func.ret }},
      hasRustCallStatus: {{ func.has_rust_call_status }},
    },
    {%- endfor %}
  },
  callbacks: {
    {%- for cb in module.callbacks %}
    "{{ cb.name }}": {
      args: [{{ cb.args.join(", ") }}],
      ret: {{ cb.ret }},
      hasRustCallStatus: {{ cb.has_rust_call_status }},
      {%- if cb.out_return %}
      outReturn: true,
      {%- endif %}
    },
    {%- endfor %}
  },
  structs: {
    {%- for s in module.structs %}
    "{{ s.name }}": [
      {%- for field in s.fields %}
      { name: "{{ field.name }}", type: {{ field.type_expr }} },
      {%- endfor %}
    ],
    {%- endfor %}
  },
} as const;

interface NativeModuleInterface {
    {%- for func in module.typed_functions %}
    {{ func.name }}(
      {%- for arg in func.arguments %}
        {{- arg.name }}: {{ arg.type_name }}
        {%- if !loop.last %}, {% endif %}
      {%- endfor %}):
      {%- match func.return_type %}{% when Some with (rt) %} {{ rt }}{% when None %} void{% endmatch %};
  {%- endfor %}
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: "{{ module.crate_name }}",
      callerUrl: import.meta.url,
      {%- match module.lib_resolution %}
      {%- when LibResolution::Colocated %}
      {%- when LibResolution::Absolute with (path) %}
      override: "{{ path }}",
      {%- when LibResolution::Require { base, triple_style } %}
      npmPackageBase: "{{ base }}",
      tripleStyle: "{{ triple_style.as_runtime_tag() }}",
      {%- endmatch %}
    });
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
{%- for def in module.typed_definitions %}
{%- match def %}
{%- when FfiDefinitionDecl::Callback(callback) %}
{% if callback.exported %}export {% endif %}type {{ callback.name }} = (
{%-   for arg in callback.arguments %}
{{- arg.name }}: {{ arg.type_name }}{% if !loop.last %}, {% endif %}
{%-   endfor %}) => {{ callback.return_type }};
{%- when FfiDefinitionDecl::Struct(ffi_struct) %}
{% if ffi_struct.exported %}export {% endif %}type {{ ffi_struct.name }} = {
  {%- for field in ffi_struct.fields %}
  {{ field.name }}: {{ field.type_name }};
  {%- endfor %}
};
{%- endmatch %}
{%- endfor %}
