// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

{%- match module.host_source %}
{%- when PlayerHostSource::NapiPackage %}
import lib from "@ubjs/node";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;
{%- when PlayerHostSource::JsiGlobal %}
import { FfiType } from "@ubjs/core";
{%- when PlayerHostSource::WasmCore %}
// Only `/core`, which is environment-neutral. Opening the `.wasm` is the
// generated `index.ts`'s job, so this module
// bundles for node, browsers and React Native alike.
import { FfiType, type ModuleDefinitions } from "@ubjs/wasm/core";
{%- endmatch %}

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

// Arrays stay mutable; readonly does not assign to `FfiTypeDesc[]`.
const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "{{ module.symbols.rustbuffer_alloc }}",
    rustbuffer_free: "{{ module.symbols.rustbuffer_free }}",
    rustbuffer_from_bytes: "{{ module.symbols.rustbuffer_from_bytes }}",
  },
  functions: {
    {%- for func in module.functions %}
    "{{ func.name }}": {
      args: [{{ func.args.join(", ") }}],
      ret: {{ func.ret }},
      hasRustCallStatus: {{ func.has_rust_call_status }},
    },
    {%- endfor %}
  },
  callbacks: {
    {%- for cb in module.callbacks %}
    "{{ cb.name }}": {
      args: [{{ cb.args.join(", ") }}],
      ret: {{ cb.ret }},
      hasRustCallStatus: {{ cb.has_rust_call_status }},
      {%- if cb.out_return %}
      outReturn: true,
      {%- endif %}
    },
    {%- endfor %}
  },
  structs: {
    {%- for s in module.structs %}
    "{{ s.name }}": [
      {%- for field in s.fields %}
      { name: "{{ field.name }}", type: {{ field.type_expr }} },
      {%- endfor %}
    ],
    {%- endfor %}
  },
}{% if module.host_source == PlayerHostSource::WasmCore %} satisfies ModuleDefinitions{% endif %};

interface NativeModuleInterface {
    {%- for func in module.typed_functions %}
    {{ func.name }}(
      {%- for arg in func.arguments %}
        {{- arg.name }}: {{ arg.type_name }}
        {%- if !loop.last %}, {% endif %}
      {%- endfor %}):
      {%- match func.return_type %}{% when Some with (rt) %} {{ rt }}{% when None %} void{% endmatch %};
  {%- endfor %}
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

let _nativeModule: NativeModuleInterface | undefined;
{%- match module.host_source %}
{%- when PlayerHostSource::WasmCore %}
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    throw new Error(
      "{{ module.crate_name }}: wasm module not initialised. Await " +
      "`uniffiInitAsync(...)` from the generated entrypoint before calling " +
      "into this module.",
    );
  }
  return _nativeModule;
};
export const PLAYER_DEFINITIONS = DEFINITIONS;
// Takes the runtime's loose record — `registerSync` cannot know this
// module's exports — and narrows it once, here, rather than at each call.
export function setNativeModule(m: Record<string, (...args: any[]) => any>) {
  _nativeModule = m as unknown as NativeModuleInterface;
}
{%- when PlayerHostSource::NapiPackage %}
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: "{{ module.crate_name }}",
      callerUrl: import.meta.url,
      {%- match module.lib_resolution %}
      {%- when Some with (resolution) %}
        {%- match resolution %}
        {%- when LibResolution::Colocated %}
        {%- when LibResolution::Name with (_name) %}
        {%- when LibResolution::Absolute with (path) %}
      override: "{{ path }}",
      {%- when LibResolution::Require { base, triple_style } %}
      npmPackageBase: "{{ base }}",
      tripleStyle: "{{ triple_style.as_runtime_tag() }}",
        {%- endmatch %}
      {%- when None %}
      {%- endmatch %}
    });
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
{%- when PlayerHostSource::JsiGlobal %}
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    {#- Keep this lib_resolution match in sync with the NapiPackage arm above when a new LibResolution variant is added. #}
    {%- match module.lib_resolution %}
    {%- when Some with (resolution) %}
      {%- match resolution %}
      {%- when LibResolution::Absolute with (path) %}
    const libPath = "{{ path }}";
      {%- when LibResolution::Colocated %}
    const libPath = "{{ module.crate_name }}";
      {%- when LibResolution::Require { base, triple_style } %}
    const libPath = "{{ base }}";
      {%- when LibResolution::Name with (name) %}
    const libPath = { name: "{{ name }}" };
      {%- endmatch %}
    {%- when None %}
    const libPath = "{{ module.crate_name }}";
    {%- endmatch %}
    const uniffi = (globalThis as any).uniffi;
    const mod_ = uniffi.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
{%- endmatch %}
export default getter;

// Structs and function types for calling back into Typescript from Rust.
{%- for def in module.typed_definitions %}
{%- match def %}
{%- when FfiDefinitionDecl::Callback(callback) %}
{% if callback.exported %}export {% endif %}type {{ callback.name }} = (
{%-   for arg in callback.arguments %}
{{- arg.name }}: {{ arg.type_name }}{% if !loop.last %}, {% endif %}
{%-   endfor %}) => {{ callback.return_type }};
{%- when FfiDefinitionDecl::Struct(ffi_struct) %}
{% if ffi_struct.exported %}export {% endif %}type {{ ffi_struct.name }} = {
  {%- for field in ffi_struct.fields %}
  {{ field.name }}: {{ field.type_name }};
  {%- endfor %}
};
{%- endmatch %}
{%- endfor %}
