// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
{%- import "TopLevelFunctionTemplate.ts" as tlf %}
{%- import "SimpleWrapperTemplate.ts" as sw %}
{%- import "StringHelperTemplate.ts" as sh %}
{%- import "CustomTypeTemplate.ts" as ct %}
{%- import "InitializationTemplate.ts" as init %}
{%- import "EnumTemplate.ts" as en %}
{%- import "ErrorTemplate.ts" as err %}
{%- import "TaggedEnumTemplate.ts" as te %}
{%- import "RecordTemplate.ts" as rec %}
{%- import "ObjectTemplate.ts" as ot %}
{%- import "CallbackInterfaceTemplate.ts" as cbit %}

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

{%- if module.flavor.supports_globalthis_native_module() || module.flavor.supports_player() %}
import nativeModule from "./{{ module.module_name }}-ffi";
{%- else %}
import * as wasmBundle from "./wasm-bindgen/index.js";
{%- endif %}
{%- for imp in module.file_imports %}
import {
{%-   for t in imp.types %} type {{ t }},{%- endfor %}
{%-   for v in imp.values %} {{ v }},{%- endfor %}
} from "{{ imp.path }}";
{%- endfor %}

{%- for conv in module.converter_imports %}
import {{ conv.default_name }} from "{{ conv.path }}";
const { {{ conv.converters|join(", ") }} } = {{ conv.default_name }}.converters;
{%- endfor %}

{%- if module.flavor.supports_plain_call_status() %}
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));
{%- else %}
const nativeModule = () => wasmBundle;
const uniffiCaller = new UniffiRustCaller(() => new wasmBundle.RustCallStatus());
{%- endif %}

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  {{ module.is_debug }};

{%- match module.namespace_docstring %}
{%- when Some with (docstring) %}
{{ docstring }}
{%- when None %}
{%- endmatch %}

// Public interface members begin here.
{%- for func in module.functions %}
{% call tlf::function(func) %}
{%- endfor %}
{%- for td in module.type_definitions %}
{%- match td %}
{%- when TsTypeDefinition::SimpleWrapper(wrapper) %}
{% call sw::simple_wrapper(wrapper) %}
{%- when TsTypeDefinition::StringHelper(helper) %}
{% call sh::string_helper(helper) %}
{%- when TsTypeDefinition::Custom(custom) %}
{% call ct::custom_type(custom) %}
{%- when TsTypeDefinition::External(_) %}
{%- when TsTypeDefinition::FlatEnum(e) %}
{% call en::flat_enum(e) %}
{%- when TsTypeDefinition::FlatError(e) %}
{% call err::flat_error(e) %}
{%- when TsTypeDefinition::TaggedEnum(e) %}
{% call te::tagged_enum(e) %}
{%- when TsTypeDefinition::Record(rec) %}
{% call rec::record(rec) %}
{%- when TsTypeDefinition::Object(obj) %}
{% call ot::object(obj) %}
{%- when TsTypeDefinition::CallbackInterface(cbi) %}
{% call cbit::callback_interface(cbi) %}
{%- endmatch %}
{%- endfor %}

{% call init::initialization(module.initialization) %}

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  {%- if !module.exported_converters.is_empty() %}
  converters: {
  {%- for converter in module.exported_converters %}
    {{ converter }},
  {%- endfor %}
  }{% endif %}
});
