// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

import lib from "@uniffi-runtime/napi/lib.js";
const { UniffiNativeModule, FfiType } = lib;

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from 'uniffi-bindgen-react-native';

const DEFINITIONS = {
  symbols: {
    rustbufferAlloc: "{{ module.symbols.rustbuffer_alloc }}",
    rustbufferFree: "{{ module.symbols.rustbuffer_free }}",
    rustbufferFromBytes: "{{ module.symbols.rustbuffer_from_bytes }}",
  },
  functions: {
    {%- for func in module.functions %}
    "{{ func.name }}": {
      args: [{{ func.args.join(", ") }}],
      ret: {{ func.ret }},
      hasRustCallStatus: {{ func.has_rust_call_status }},
    },
    {%- endfor %}
  },
  callbacks: {
    {%- for cb in module.callbacks %}
    "{{ cb.name }}": {
      args: [{{ cb.args.join(", ") }}],
      ret: {{ cb.ret }},
      hasRustCallStatus: {{ cb.has_rust_call_status }},
      {%- if cb.out_return %}
      outReturn: true,
      {%- endif %}
    },
    {%- endfor %}
  },
  structs: {
    {%- for s in module.structs %}
    "{{ s.name }}": [
      {%- for field in s.fields %}
      { name: "{{ field.name }}", type: {{ field.type_expr }} },
      {%- endfor %}
    ],
    {%- endfor %}
  },
} as const;

interface NativeModuleInterface {
    {%- for func in module.typed_functions %}
    {{ func.name }}(
      {%- for arg in func.arguments %}
        {{- arg.name }}: {{ arg.type_name }}
        {%- if !loop.last %}, {% endif %}
      {%- endfor %}):
      {%- match func.return_type %}{% when Some with (rt) %} {{ rt }}{% when None %} void{% endmatch %};
  {%- endfor %}
}

let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    {%- match module.lib_path %}
    {%- when Some with (path) %}
    const libPath = "{{ path }}";
    {%- when None %}
    const libPath = process.env.UNIFFI_LIB_PATH;
    if (!libPath) {
      throw new Error(
        "No library path available. " +
        "Set the UNIFFI_LIB_PATH environment variable to the path of the shared library."
      );
    }
    {%- endmatch %}
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
{%- for def in module.typed_definitions %}
{%- match def %}
{%- when FfiDefinitionDecl::Callback(callback) %}
{% if callback.exported %}export {% endif %}type {{ callback.name }} = (
{%-   for arg in callback.arguments %}
{{- arg.name }}: {{ arg.type_name }}{% if !loop.last %}, {% endif %}
{%-   endfor %}) => {{ callback.return_type }};
{%- when FfiDefinitionDecl::Struct(ffi_struct) %}
{% if ffi_struct.exported %}export {% endif %}type {{ ffi_struct.name }} = {
  {%- for field in ffi_struct.fields %}
  {{ field.name }}: {{ field.type_name }};
  {%- endfor %}
};
{%- endmatch %}
{%- endfor %}
