// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
 } from 'uniffi-bindgen-react-native';

interface NativeModuleInterface {
    {%- for func in module.functions %}
    {{ func.name }}(
      {%- for arg in func.arguments %}
        {{- arg.name }}: {{ arg.type_name }}
        {%- if !loop.last %}, {% endif %}
      {%- endfor %}):
      {%- match func.return_type %}{% when Some with (rt) %} {{ rt }}{% when None %} void{% endmatch %};
  {%- endfor %}
}

// Casting globalThis to any allows us to look for `{{ module.module_name }}`
// if it was added via JSI.
//
// We use a getter here rather than simply `globalThis.{{ module.module_name }}` so that
// if/when the startup sequence isn't just so, an empty value isn't inadvertantly cached.
const getter: () => NativeModuleInterface = () => (globalThis as any).{{ module.module_name }};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
{%- for def in module.definitions %}
{%- match def %}
{%- when FfiDefinitionDecl::Callback(callback) %}
{% if callback.exported %}export {% endif %}type {{ callback.name }} = (
{%-   for arg in callback.arguments %}
{{- arg.name }}: {{ arg.type_name }}{% if !loop.last %}, {% endif %}
{%-   endfor %}) => {{ callback.return_type }};
{%- when FfiDefinitionDecl::Struct(ffi_struct) %}
{% if ffi_struct.exported %}export {% endif %}type {{ ffi_struct.name }} = {
  {%- for field in ffi_struct.fields %}
  {{ field.name }}: {{ field.type_name }};
  {%- endfor %}
};
{%- endmatch %}
{%- endfor %}

// UniffiRustFutureContinuationCallback is generated as part of the component interface's
// ffi_definitions. However, we need it in the runtime.
// We could:
// (a) do some complicated template logic to ensure the declaration is not generated here (possible)
// (b) import the generated declaration into the runtime (m a y b e) or…
// (c) generate the declaration anyway, and use a different declaration in the runtime.
//
// We chose (c) here as the simplest. In addition, we perform a compile time check that
// the two versions of `UniffiRustFutureContinuationCallback` are structurally equivalent.
//
// If you see the error:
// ```
// Type 'true' is not assignable to type 'false'.(2322)
// ```
// Then a new version of uniffi has changed the signature of the callback. Most likely, code in
// `typescript/src/async-rust-call.ts` will need to be changed.
//
// If you see the error:
// ```
// Cannot find name 'UniffiRustFutureContinuationCallback'. Did you mean 'RuntimeUniffiRustFutureContinuationCallback'?(2552)
// ```
// then you may not be using callbacks or promises, and uniffi is now not generating Futures and callbacks.
// You should not generate this if that is the case.
//
// ('You' being the bindings generator maintainer).
const isRustFutureContinuationCallbackTypeCompatible: UniffiStructuralEquality<
  RuntimeUniffiRustFutureContinuationCallback,
  UniffiRustFutureContinuationCallback
> = true;
const isUniffiForeignFutureTypeCompatible: UniffiStructuralEquality<
  RuntimeUniffiForeignFuture,
  UniffiForeignFuture
> = true;
