// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

{%- if !module.strict_type_checking %}
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
{%- endif %}

{%- if module.flavor.is_jsi() %}
import nativeModule from "./{{ module.module_name }}-ffi";
{%- else %}
import * as wasmBundle from "./wasm-bindgen/index.js";
{%- endif %}
import type {
  {%- for def in module.ffi_exported_definitions %}
  {{ def.name() }},
  {%- endfor %}
} from "./{{ module.module_name }}-ffi";

{%- for entry in module.type_imports %}
{%-   let file = entry.0 %}
{%-   let things = entry.1 %}
import {
{%-   for thing in things %}
{%-     match thing %}
{%-       when ImportedItem::Type with (type_) %}
  type {{ type_ }}
{%-       when ImportedItem::Value with (type_) %}
  {{ type_ }}
{%-     endmatch %}
{%-     if !loop.last %}, {% endif %}
{%-   endfor %} } from "{{ file }}";
{%- endfor %}

// Get converters from the other files, if any.
{%- for entry in module.imported_converters %}
import {{ entry.0.1 }} from "{{ entry.0.0 }}";
{%- endfor %}
{%- for entry in module.imported_converters %}
{%-   let converters = entry.1 %}
const {
{%-   for converter in converters %}
        {{- converter }},
{%-   endfor %}
} = {{ entry.0.1 }}.converters;
{%- endfor %}

{%- if module.flavor.is_jsi() %}
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));
{%- else %}
const nativeModule = () => wasmBundle;
const uniffiCaller = new UniffiRustCaller(() => new wasmBundle.RustCallStatus());
{%- endif %}

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  {{ module.is_debug }};

{%- match module.namespace_docstring %}
{%- when Some with (docstring) %}
{{ docstring }}
{%- when None %}
{%- endmatch %}

// Public interface members begin here.
{{ module.render_all_types() }}

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  {%- if !module.exported_converters.is_empty() %}
  converters: {
  {%- for converter in module.exported_converters %}
    {{ converter }},
  {%- endfor %}
  }{% endif %}
});
