// Generated by uniffi-bindgen-react-native
// The player must be a direct dependency of the app: autolinking reads only
// the app's package.json, so a transitive @ubjs/react-native never installs.
import "@ubjs/react-native";

// Load-bearing order: imports are hoisted, so the guard runs after the
// generated index has initialized every module (checksums and vtables) but
// before any of them opens the library, whose getters are lazy.
if (typeof (globalThis as any).uniffi === "undefined") {
  throw new Error(
    "@ubjs/react-native must be a direct dependency of the app; add it and re-run pod install",
  );
}
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.jsi2_bindings_ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
export * from './{{ bindings }}';
export { default } from './{{ bindings }}';
{# space #}
