// Generated by uniffi-bindgen-react-native
// The player must be a direct dependency of the app: autolinking reads only
// the app's package.json, so a transitive @ubjs/react-native never installs.
import "@ubjs/react-native";

// Load-bearing order: imports are hoisted, so the guard runs after every
// binding module is evaluated but before any of them opens the library, whose
// getters are lazy.
if (typeof (globalThis as any).uniffi === "undefined") {
  throw new Error(
    "@ubjs/react-native must be a direct dependency of the app; add it and re-run pod install",
  );
}
{%- let root = self.project_root() %}
{%- let bindings = self.config.project.jsi2_bindings_ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}
{%- for m in self.config.modules %}
export * from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}
{%- for m in self.config.modules %}
import * as {{ m.ts() }} from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}

// Checksums and callback vtables; the first of these opens the library.
{%- for m in self.config.modules %}
{{ m.ts() }}.default.initialize();
{%- endfor %}

// Parity with the web entrypoint, which has a module to fetch first.
export async function uniffiInitAsync() {}

export default {
{%- for m in self.config.modules %}
  {{ m.ts() }},
{%- endfor %}
};
{# space #}
