// Generated by uniffi-bindgen-react-native
package {{ self.config.project.android.package_name() }};

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import java.util.Collections;
import java.util.List;

// Autolinking only includes a library whose sources define a ReactPackage.
// The player owns every native module, so this one is deliberately empty.
public class {{ self.config.project.module_cpp() }}Package implements ReactPackage {
  @Override
  public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
    return Collections.emptyList();
  }

  @Override
  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
    return Collections.emptyList();
  }
}
