name: Test Turbo Modules

inputs:
  platform:
    description: One of android, ios
    required: true
  bobVersion:
    description: The version of create-react-native-library
    required: true
  rnVersion:
    description: The version of React Native
    required: true

runs:
  using: "composite"
  steps:
    - name: Install cargo-ndk
      if: ${{ inputs.platform == 'android' }}
      shell: bash
      run: |
        cargo install cargo-ndk

    - name: Install JDK
      if: ${{ inputs.platform == 'android' }}
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Install Rust toolchains
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.platform == 'ios' && 'aarch64-apple-ios-sim' || 'aarch64-linux-android' }}

    - name: Ensure git identity
      shell: bash
      run: |
        # The comparison tests depend on create-react-native-library initialising
        # a git repository with a first commit. This will silently fail if no git
        # identity was set up which apparently is the case on some runners. Since
        # this action doesn't actually push any commits, we just set up a fake
        # identity.
        if [[ -z $(git config user.name) ]]; then
          git config --global user.name "Lord Mergealot"
        fi
        if [[ -z $(git config user.email) ]]; then
          git config --global user.email "lord@squash.git"
        fi

    - name: Comparison test the turbo-module generation
      shell: bash
      run: |
        ./scripts/test-turbo-modules.sh \
          --slug '@my-org/my-lib' \
          --ubrn-config integration/fixtures/compat/ubrn.config.yaml \
          --builder-bob-version ${{ inputs.bobVersion }} \
          --rn-version ${{ inputs.rnVersion }} \
          --package-json-mixin integration/fixtures/compat/package.json \
          --react-native-config integration/fixtures/compat/react-native.config.js \
          ../turbo-module-comparison-testing

    - name: Generate & build turbo module
      # Disable the perma-failing android
      if: ${{ inputs.platform != 'android' }}
      shell: bash
      run: |
        ./scripts/test-turbo-modules.sh \
          --slug '@my-org/my-lib' \
          --ubrn-config integration/fixtures/compat/ubrn.config.yaml \
          --builder-bob-version ${{ inputs.bobVersion }} \
          --rn-version ${{ inputs.rnVersion }} \
          --package-json-mixin integration/fixtures/compat/package.json \
          --react-native-config integration/fixtures/compat/react-native.config.js \
          --${{ inputs.platform }} \
          --pack \
          ../turbo-module-for-building
