name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Install yarn
        run: cargo xtask bootstrap yarn

      - name: Check Typescript format
        run: cargo xtask fmt --check typescript

      - name: Check Rust format
        run: cargo xtask fmt --check rust

  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

  unit-tests:
    name: 🧪 Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ~/.cargo/bin

      - name: Run tests
        run: cargo nextest run --verbose --workspace --exclude 'uniffi-example-*' --exclude 'uniffi-fixture-*' --exclude 'uniffi-runtime-tests' --no-capture

      - name: Run tests for binaries
        run: cargo nextest run --bins --no-capture

  integration-tests-jsi-bindings:
    name: 🧩 Integration tests (JSI bindings)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@nextest

      - name: Install tooling for building C++
        run: sudo apt-get install -y cmake ninja-build

      - name: Installing hermes and test-runner
        run: |
          cargo xtask bootstrap

      - name: Run tests of generated JSI bindings
        run: cargo nextest run -E 'test(jsi::)' --no-capture

  integration-tests-wasm-bindings:
    name: 🧩 Integration tests (WASM bindings)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@nextest

      - name: Installing
        run: cargo xtask bootstrap yarn

      - name: Installing WASM
        run: rustup target add wasm32-unknown-unknown

      - name: Installing wasm-bindgen
        run: cargo install wasm-bindgen-cli --version 0.2.100 --locked

      - name: Run tests of generated WASM bindings
        run: cargo nextest run -E 'test(wasm::)' --no-capture

  integration-tests-checkout:
    name: 🧩 Integration tests (checkout)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests for checkout command
        run: ./scripts/run-checkout-tests.sh
