name: Compat / Android

on:
  schedule:
    - cron: "0 0 * * *" # Once a day at midnight
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  compat:
    strategy:
      matrix:
        bob-version:
          - 0.48.9
          - 0.49.5
        rn-version:
          - 0.76.9
          - 0.77.2
          - 0.78.2
      fail-fast: false

    runs-on: ubuntu-latest
    name: "bob ${{ matrix.bob-version }} / rn ${{ matrix.rn-version }} / android"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-turbo-modules
        with:
          platform: android
          bobVersion: ${{ matrix.bob-version }}
          rnVersion: ${{ matrix.rn-version }}
