name: Compat / Android

on:
  schedule:
    - cron: "0 0 * * 1" # Once a week at midnight on Monday
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  compat:
    strategy:
      matrix:
        bob-version:
          - 0.49.10
        rn-version:
          - 0.77.2
          - 0.81.4
      # Uncomment to debug failures
      # fail-fast: false

    runs-on: ubuntu-latest
    name: "bob ${{ matrix.bob-version }} / rn ${{ matrix.rn-version }} / android"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-turbo-modules
        with:
          platform: android
          bobVersion: ${{ matrix.bob-version }}
          rnVersion: ${{ matrix.rn-version }}
